server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service-auth
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/customers/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "NDM1MTQzMjY0NjI5NDkyODQ0MTYyNTQzMjA0NjI4Mjk0MjQ0MjM1MjY0NjI5NDkyODQ0MTYyNTQzMjA0NjI4Mjk0MjQ0MjM1Mg=="

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/